apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-quarkus-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-quarkus-k8s
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-quarkus-k8s
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: brunopenha/demo-quarkus-k8s:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: demo-quarkus-k8s
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: demo-quarkus-k8s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-quarkus-k8s
data:
  env.name: "dev_3"